/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SuperSimpleStockMarket;

public class App {
    public String getGreeting() {
        return "Welcome to Super Simple Stock Market";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
